@startuml usecase

left to right direction
' skinparam packageStyle rectangle

actor User as u
actor Database as db

package "Nutrtion Compass Website" {
    package "User Management" {
        usecase (Register) as register
        usecase (Hash Password) as hash
        usecase (Login) as login
        usecase (Check Validity) as check_validity
        usecase (Credential Error) as credential_error
        usecase (Verify Email) as verify_email
        usecase (Logout) as logout
        usecase (View Profile) as view_profile
        usecase (Edit Profile) as edit_profile
    }

    package "User Dashboard" {
        usecase (View Dashboard) as view_dash
        usecase (View Food History) as view_food_hist
        usecase (Add New or Existing Food Item) as add_food_dash
        usecase (Nutrition Calculations) as nutr_calc
    }

    package "Food History" {
        usecase (Add Food Item) as add_food
        usecase (Barcode Scanner) as scan_bar
        usecase (Search Food Item) as search_food
        usecase (Edit Food Item) as edit_food
        usecase (Existence Check) as exist_check
        usecase (Delete Food Item) as delete_food
        usecase (View Food Details) as view_food_item
    }

    ' Registration
    u --> register
    register ..> hash : <<include>>
    hash --> db

    ' User Management
    u -> login
    login ..> check_validity : <<include>>
    login ..> credential_error : <<extend>>
    check_validity <--> db
    u --> logout
    u --> view_profile
    view_profile ..> edit_profile : <<include>>
    edit_profile <--> db
    u --> view_dash
    verify_email <--> db

    ' Dashboard
    view_dash --> view_food_hist
    view_dash --> nutr_calc
    view_dash --> add_food_dash

    ' Food History
    view_food_hist --> add_food
    add_food ..> scan_bar : <<include>>
    view_food_hist --> search_food
    view_food_hist --> edit_food
    view_food_hist --> delete_food
    view_food_hist --> view_food_item
    edit_food ..> exist_check : <<include>>
    delete_food ..> exist_check : <<include>>
    exist_check <--> db
    view_food_item <-- db
    search_food <-- db
    scan_bar <--> db
}

@enduml